%YAML:1.0
#Q_mat:  !!opencv-matrix
#   rows: 4
#   cols: 4
#   dt: d
#   data: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
Q_mat:  !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [   1.        ,    0.        ,    0.        , -376.        ,
            0.        ,    1.        ,    0.        , -376.        ,
          0.        ,    0.        ,    0.        ,  376.        ,
          0.        ,    0.        ,   -9.43396226,    0.        ]  # -9.43 if x_right > x_left

