%YAML:1.0

cams:
   -Mode: "stereo" #forward
    camMat1:  !!opencv-matrix
        rows: 3
        cols: 3
        dt: f
        data: [376,0,376,0,376,240,0,0,1]  # [360.0652897865692, 0.0, 406.6650580307593, 0.0, 363.2195731683743, 256.20533579714373, 0.0, 0.0, 1.0]
    camMat2:  !!opencv-matrix
        rows: 3
        cols: 3
        dt: f
        data: [376,0,376,0,376,240,0,0,1] #[360.0652897865692, 0.0, 406.6650580307593, 0.0, 363.2195731683743, 256.20533579714373, 0.0, 0.0, 1.0]
    
    camRTMat:  !!opencv-matrix
        rows: 4
        cols: 4
        dt: f
        data: [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]
    QMat:  !!opencv-matrix
        rows: 4
        cols: 4
        dt: f
        data: [   1.        ,    0.        ,    0.        , -376.        ,
                0.        ,    1.        ,    0.        , -376.        ,
              0.        ,    0.        ,    0.        ,  376.        ,
              0.        ,    0.        ,   -9.43396226,    0.        ]  # -9.43 if x_right > x_left
   -Mode: "stereo"  #left
    camMat1:  !!opencv-matrix
        rows: 3
        cols: 3
        dt: f
        data: [376,0,376,0,376,240,0,0,1] #[360.0652897865692, 0.0, 406.6650580307593, 0.0, 363.2195731683743, 256.20533579714373, 0.0, 0.0, 1.0]
    camMat2:  !!opencv-matrix
        rows: 3
        cols: 3
        dt: f
        data: [376,0,376,0,376,240,0,0,1] # [360.0652897865692, 0.0, 406.6650580307593, 0.0, 363.2195731683743, 256.20533579714373, 0.0, 0.0, 1.0]
    
    camRTMat:  !!opencv-matrix
        rows: 4
        cols: 4
        dt: f
        data: [0,-1,0,0,1,0,0,0,0,0,1,0,0,0,0,1]
    QMat:  !!opencv-matrix
        rows: 4
        cols: 4
        dt: f
        data: [   1.        ,    0.        ,    0.        , -376.        ,
                0.        ,    1.        ,    0.        , -376.        ,
              0.        ,    0.        ,    0.        ,  376.        ,
              0.        ,    0.        ,   -9.43396226,    0.        ]  # -9.43 if x_right > x_left
